### ISSUE TITLE
Exponentially slow list operations

### ISSUE THREAD

**Issue by OvermindDL1** [expede/witchcraft#35]
Noticed a few areas like https://github.com/expede/witchcraft/blob/master/lib/witchcraft/apply.ex#L59 where right list concatenation is performed, this is *extremely* slow on the BEAM as it forces the entire list to be recreated on every operation as it is built up, thus giving it exponential time based on list length.  This example should probably be an `Enum.map/2` instead of a fold (in fact a lot of the operations in `Foldable` could be substantially optimized as many are taking exponential or linear time when they could be done much faster).

**Comment by expede** [comment]
Yeah, I can't say that I'm surprised. Thanks for the reminder!

Most of the library is commented out right now. The next step is to actually get stuff working, and then go back in and make the internals more suited to Elixir rather than just copy/pasting from the Haskell Prelude 🤦‍♀️

**Comment by OvermindDL1** [comment]
> Most of the library is commented out right now. The next step is to actually get stuff working, and then go back in and make the internals more suited to Elixir rather than just copy/paste/translating from the Haskell Prelude 😜

Hehe, I figured that based on the amount of things still commented out.  ^.^
Just thought I'd open an issue so it would not be forgotten.  :-)

**Comment by expede** [comment]
Okay, so Foldable in particular: worked both the instances _and_ fallback to `Enum` for built in types that implement Enumerable 👍 Also wrote a Benchfella suite as a starting point to improve performance over time.
