### ISSUE TITLE
GraphQL example

### ISSUE THREAD

**Issue by izaakschroeder** [expede/witchcraft#6]
Be able to do something like: http://underscore.io/blog/posts/2015/04/14/free-monads-are-simple.html where a GraphQL request requires multiple sources to collect its information for a given request.

**Comment by expede** [comment]
Getting there slowly but surely! Just added the basics of the Johansen Free formulation, and other niceties like `liftF` are coming soon :smile:

A GQL example should be straightforward, though GQL is already in an an interpretable form, so the DSL might be overkill. We might also want to explore using the Free Applicative and CoFree for this problem. (I really want CoFree in here, anyways :wink:)
