### ISSUE TITLE
Is the "Properties" section in `Witchcraft.Foldable` documentation a note for maintainers?

### ISSUE THREAD

**Issue by toraritte** [expede/witchcraft#64]
I wasn't able to make sense of the ["Properties" section in `Witchcraft.Foldable`](https://hexdocs.pm/witchcraft/Witchcraft.Foldable.html#module-properties), but then I don't even know what free theorems are (found [this](https://stackoverflow.com/questions/12421085/good-introduction-to-free-theorems) and [this](https://www.reddit.com/r/haskellquestions/comments/6fkufo/free_theorems/) on the topic) or what properties `Foldable` has. Based on the wording, it also seemed as if this is a general note for maintainers. Am I on the right track?

> **Properties**
> People are working on Foldable properties. This is one of the exceptions to there needing to conform to properties. In the meantime, we are testing that naturality is preserved, which is be a free theorm.
> 
> If that fails, something is very wrong with the instance.

**Comment by expede** [comment]
>  it also seemed as if this is a general note for maintainers

Yes and no. `Foldable` goes against the philosophy of principled type classes, as we would expect it to have testable properties. The props that it does have are trivial, so testing them should not fail under any circumstances. if it does, then the instance is severely broken.
